import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import Layout from '../components/Layout'
import { api } from '../lib/api'
import type { Project } from '../lib/types'
import { ArrowDown, ArrowUp, MessageCircle, Minus, X } from 'lucide-react'

type Risk = { issue_id: number; title: string; severity: string; priority: string; status: string; updated_at?: string; risk_score: number; risk_level: string; reasons: string[]; reopen_count: number; age_days: number; recommendation: string }
type Radar = { project_id?: number | null; project_name?: string | null; role?: string; role_label?: string; issues: Risk[]; role_issues?: Risk[]; summary: Record<string, number>; methodology: string; overall?: { score: number | null; level: string; explanation: string }; top_risks?: Risk[]; factor_breakdown?: Record<string, number>; recommendations?: string[]; risk_trend?: { direction: 'up' | 'down' | null; label: string; message: string } }

export default function RiskRadarPage() {
  const [selectedRisk, setSelectedRisk] = useState<Risk | null>(null)
  const [selectedProjectId, setSelectedProjectId] = useState<number | ''>('')
  const { data: projects = [], isLoading: isProjectsLoading } = useQuery<Project[]>({ queryKey: ['projects'], queryFn: async () => (await api.get('/api/projects')).data })
  useEffect(() => {
    if (selectedProjectId === '' && projects[0]) setSelectedProjectId(projects[0].id)
  }, [projects, selectedProjectId])
  const { data, isLoading } = useQuery<Radar>({ queryKey: ['risk-radar', selectedProjectId], enabled: selectedProjectId !== '', queryFn: async () => (await api.get('/api/risk', { params: { project_id: selectedProjectId } })).data })
  const roleIssues = data?.role_issues ?? data?.issues ?? []
  const isReporter = data?.role === 'Reporter'
  const selectedProject = projects.find(project => project.id === selectedProjectId)
  const overall = data?.overall
  const factorBreakdown = data?.factor_breakdown ?? {}
  const factorMax = Math.max(1, ...Object.values(factorBreakdown).map(value => Math.abs(value)))
  const askAssistant = (question: string, context = '') => {
    const projectContext = selectedProjectId === '' ? '' : `Selected project ID: ${selectedProjectId}; name: ${selectedProject?.project_name ?? data?.project_name ?? 'Unknown'}`
    window.dispatchEvent(new CustomEvent('bugflow-assistant-prefill', { detail: [question, projectContext, context ? `Current Risk Radar context: ${context}` : ''].filter(Boolean).join('\n\n') }))
  }
  const trendIcon = data?.risk_trend?.direction === 'up' ? <ArrowUp size={15} /> : data?.risk_trend?.direction === 'down' ? <ArrowDown size={15} /> : <Minus size={15} />
  const nextStep = (status: string) => status === 'Resolved' ? 'Verification' : status === 'Verified' ? 'Closure' : status === 'Open' || status === 'Assigned' ? 'Investigation / resolution' : status
  return <Layout title="Defect Risk Radar">
    <div className="mt-1 flex flex-wrap items-center gap-3"><label htmlFor="risk-project" className="text-sm font-medium">Project</label><select id="risk-project" value={selectedProjectId} onChange={event => setSelectedProjectId(event.target.value ? Number(event.target.value) : '')} disabled={isProjectsLoading || projects.length === 0} className="min-w-56 rounded-xl border border-border bg-card px-3 py-2 text-sm"><option value="">{isProjectsLoading ? 'Loading projects...' : projects.length ? 'Select project' : 'No projects available'}</option>{projects.map(project => <option key={project.id} value={project.id}>{project.project_name}</option>)}</select></div>
    {selectedProjectId === '' ? <p className="mt-6 rounded-2xl border border-border bg-card p-5 text-sm text-muted-foreground">No project selected. Choose an authorized project to view its Risk Radar.</p> : isLoading ? <p className="mt-6 rounded-2xl border border-border bg-card p-5 text-sm text-muted-foreground">Loading Risk Radar...</p> : <>
    <p className="text-sm text-muted-foreground">{data?.role_label || 'Role-aware risk overview'} · {data?.methodology || 'Transparent issue-level risk signals.'}</p>
    <section className="mt-5 grid gap-4 xl:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-border bg-card p-5 shadow-glow"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.25em] text-muted-foreground">Overall Project Risk</p><p className="mt-2 text-4xl font-semibold text-primary">{overall?.score == null ? 'No Data' : `${overall.score} / 100`}</p><p className="mt-1 font-medium">{overall?.level ?? 'Loading'}</p></div><button type="button" onClick={() => askAssistant('Why is this project currently at risk, which defects should we prioritize, and what actions should the team take?', `overall ${overall?.score ?? 'No Data'} / 100 (${overall?.level ?? 'No Data'}); counts ${JSON.stringify(data?.summary ?? {})}; top risks ${(data?.top_risks ?? []).map(issue => `BUG-${issue.issue_id} ${issue.risk_score}/100`).join(', ') || 'none'}; factors ${JSON.stringify(factorBreakdown)}`)} className="flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-sm font-medium text-foreground"><MessageCircle size={16} /> Ask Assistant</button></div><div className="mt-4 flex items-center gap-2 text-sm text-muted-foreground">{trendIcon}<span>Risk Trend: {data?.risk_trend?.label ?? 'Loading'}</span></div><p className="mt-3 text-sm text-muted-foreground">{overall?.explanation ?? 'Current authorized risk data is loading.'}</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4">{['Critical', 'High', 'Medium', 'Low'].map(level => <div key={level} className="rounded-xl border border-border bg-background p-3"><p className="text-xs text-muted-foreground">{level}</p><p className="mt-1 text-xl font-semibold">{data?.summary[level] ?? 0}</p></div>)}</div></div>
      <div className="rounded-3xl border border-border bg-card p-5 shadow-glow"><p className="text-sm uppercase tracking-[0.25em] text-muted-foreground">Risk Factors</p><div className="mt-4 space-y-3">{Object.entries(factorBreakdown).map(([factor, value]) => <div key={factor}><div className="flex justify-between text-xs"><span className="capitalize">{factor}</span><span className="text-muted-foreground">{value}</span></div><div className="mt-1 h-2 rounded bg-border"><div className="h-2 rounded bg-primary" style={{ width: `${Math.min(100, (Math.abs(value) / factorMax) * 100)}%` }} /></div></div>)}</div>{data?.risk_trend?.message && <p className="mt-4 text-xs text-muted-foreground">{data.risk_trend.message}</p>}</div>
    </section>
    <section className="mt-4 grid gap-4 lg:grid-cols-[1fr_.9fr]"><div className="rounded-3xl border border-border bg-card p-5"><p className="text-sm uppercase tracking-[0.25em] text-muted-foreground">Top Risks</p><div className="mt-3 space-y-2">{(data?.top_risks ?? []).length ? data?.top_risks?.map(issue => <Link key={issue.issue_id} to={`/issues/${issue.issue_id}`} className="flex items-center justify-between rounded-xl border border-border bg-background p-3 text-sm hover:border-primary"><span>BUG-{issue.issue_id} · {issue.title}</span><span className="font-medium text-primary">{issue.risk_score}/100 · {issue.risk_level}</span></Link>) : <p className="text-sm text-muted-foreground">No authorized risks available.</p>}</div></div><div className="rounded-3xl border border-border bg-card p-5"><p className="text-sm uppercase tracking-[0.25em] text-muted-foreground">Recommended Actions</p><ul className="mt-3 space-y-2 text-sm text-muted-foreground">{(data?.recommendations ?? []).length ? data?.recommendations?.map(action => <li key={action}>• {action}</li>) : <li>No action recommendations are available.</li>}</ul></div></section>
    <div className="mt-5 grid gap-3 sm:grid-cols-4">{['Critical', 'High', 'Medium', 'Low'].map(level => <div key={level} className="rounded-2xl border border-border bg-card p-4"><p className="text-sm text-muted-foreground">{level} risk</p><p className="mt-1 text-2xl font-semibold">{data?.summary[level] ?? 0}</p></div>)}</div>
    <section className="mt-6 rounded-3xl border border-border bg-card p-5 shadow-glow"><h2 className="font-semibold">{isReporter ? 'My Issue Risk' : data?.role_label || 'Role-specific risk'}</h2>{isLoading ? <p className="mt-4 text-sm text-muted-foreground">Loading risk signals…</p> : roleIssues.length === 0 ? <p className="mt-4 text-sm text-muted-foreground">{isReporter ? 'No issues have been reported by you yet.' : 'No matching issues found.'}</p> : <div className="mt-4 space-y-3">{roleIssues.map(issue => <div key={issue.issue_id} className="rounded-xl border border-border bg-background p-4 hover:border-primary"><div className="flex flex-wrap items-start justify-between gap-3"><Link to={`/issues/${issue.issue_id}`} className="min-w-0 flex-1"><p className="font-medium">BUG-{issue.issue_id} — {issue.title}</p><p className="mt-1 text-xs text-muted-foreground">{issue.severity} · {issue.priority} · {issue.status}</p></Link><div className="text-right"><p className="text-xl font-semibold text-primary">{issue.risk_score}/100</p><p className="text-xs text-muted-foreground">{issue.risk_level}</p></div></div><div className="mt-3 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2"><span>Why: {issue.reasons.join(' · ')}</span><span>Next step: {nextStep(issue.status)}</span><span>Progress: {issue.status}</span>{issue.updated_at && <span>Updated: {new Date(issue.updated_at).toLocaleString()}</span>}<button type="button" onClick={() => setSelectedRisk(issue)} className="justify-self-start font-medium text-primary hover:underline">Explain Risk</button><button type="button" onClick={() => askAssistant(`Why is BUG-${issue.issue_id} considered ${issue.risk_level.toLowerCase()} risk, and what should the team do next?`)} className="flex items-center gap-1 justify-self-start font-medium text-primary hover:underline"><MessageCircle size={13} /> Ask Assistant</button></div></div>)}</div>}</section>
    {!isReporter && <section className="mt-6 rounded-3xl border border-border bg-card p-5"><h2 className="font-semibold">Ranked issues</h2><div className="mt-4 space-y-2">{(data?.issues ?? []).slice(0, 5).map(issue => <Link key={issue.issue_id} to={`/issues/${issue.issue_id}`} className="block text-sm text-primary hover:underline">BUG-{issue.issue_id} — {issue.title} ({issue.risk_level})</Link>)}</div></section>}
    {selectedRisk && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-labelledby="risk-explanation-title"><section className="w-full max-w-lg rounded-3xl border border-border bg-card p-6 shadow-glow"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">Explain Risk</p><h2 id="risk-explanation-title" className="mt-1 text-xl font-semibold">BUG-{selectedRisk.issue_id} — {selectedRisk.title}</h2></div><button type="button" onClick={() => setSelectedRisk(null)} aria-label="Close risk explanation" className="text-muted-foreground hover:text-foreground"><X size={18} /></button></div><div className="mt-5 flex items-end justify-between gap-4"><div><p className="text-4xl font-semibold text-primary">{selectedRisk.risk_score}<span className="text-lg text-muted-foreground">/100</span></p><p className="text-sm text-muted-foreground">Risk Score</p></div><p className="rounded-full bg-primary/10 px-3 py-1 text-sm font-medium text-primary">{selectedRisk.risk_level}</p></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-muted-foreground">Status</p><p className="font-medium">{selectedRisk.status}</p></div><div><p className="text-muted-foreground">Severity / Priority</p><p className="font-medium">{selectedRisk.severity} / {selectedRisk.priority}</p></div><div><p className="text-muted-foreground">Age</p><p className="font-medium">{selectedRisk.age_days} day(s)</p></div><div><p className="text-muted-foreground">Reopened</p><p className="font-medium">{selectedRisk.reopen_count} time(s)</p></div></div><div className="mt-5"><p className="text-sm font-semibold">Why?</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">{selectedRisk.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul></div><div className="mt-5 rounded-xl border border-border bg-background p-3 text-sm"><p className="font-semibold">Recommended Action</p><p className="mt-1 text-muted-foreground">{selectedRisk.recommendation}</p></div></section></div>}
  </>}
  </Layout>
}
